name: ai_dang
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.19.2
  image_picker: ^0.8.5
  flutter_screenutil: ^5.4.0
  table_calendar: ^3.0.5
  flutter_speed_dial: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

fonts:
  - family: Noto_Sans_KR
    fonts:
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Thin.otf
        weight: 200
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Light.otf
        weight: 300
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Regular.otf
        weight: 400
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Medium.otf
        weight: 500
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Bold.otf
        weight: 700
      - asset: assets/font/Noto_Sans_KR/NotoSansKR-Black.otf
        weight: 900